covid_symptoms = [
    'Fever',
    'Chills',
    'Severe cough',
    'Shortness of breath',
    'Difficulty breathing',
    'Fatigue',
    'Muscle aches',
    'Body aches',
    'Headache',
    'New loss of taste',
    'New loss of smell',
    'Sore throat',
    'Congestion',
    'Runny nose',
    'Nausea',
    'Vomiting',
    'Diarrhea',
    'Dizziness',
    'Loss of color in face and finger tips',
    'Wheezing'

]

non_covid_symptoms = [
    'Fever',
    'Chills',
    'Cough',
    'Shortness of breath',
    'Difficulty breathing',
    'Fatigue',
    'Muscle cramps',
    'Body aches',
    'Headache',
    'Sore throat',
    'Congestion',
    'Runny nose',
    'Nausea',
    'Vomiting',
    'Diarrhea',
    'Trouble sleeping',
    'Weight gain',
    'Constipation',
    'Hives',
    'Hair loss',
    'Hot flashes',
    'Ringing in ears',
    'Nose bleeding',
    'Swollen gums',
    'Irregular heartbeat',
    'Sensitive to light',
    'Drastic mood swings',
    'Shaking or trembling hands',
    'Puffy eyelids and swelling',
    'Stomach cramps',
    'Skin cracking and peeling',
    'White patches on tongue',
    'Cloudy vision',
    'Restlessness',
    'Vision loss',
    'Knee swelling',
    'Vomiting blood',
    'Acute lower back pain',
    'Burning sensation while urinating',
    'Auditory Hallucinations',
    'Visual Hallucinations',
    'Skin blisters and welts',
    'Skin rash and yellow skin',
    'Slurred speech',
    'Fainting',
    'Chronic seizures',
    'Frequent urination',
    'Foot swelling and pain',
    'Painful bowel movements',
    'Ear aches',
    'Excessive gas',
    'Muscle cramps or spasms',
    'Joint wrist pain',
    'Joint ankle pain'

]

false_symptoms = [
    'Cough',
    'Fatigue',
    'Headache',
    'Congestion',
    'Runny nose',
    'Diarrhea',
    'Nose bleeding',
]
